config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'homes/about'
  resources :users, only: %i(show edit update index) do
    resource :relationships, only: %i(create destroy)
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
    resource :favorite, only: %i(create destroy)
    resources :post_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  mount_uploader :image, ImageUploader
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # フォロー機能
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def follow(user_id)
    follower.create!(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when User
      users_path
    end
   end

  def after_sihn_out_path_for(resource)
    case resource
    when User
      root_path
    end
   end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :post_code, :address, :email])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	user = User.find(params[:user_id])
  	comment = current_user.postcomments.new(post_comment_parms)
  	comment.user_id = user.id
  	comment.save
  	redirect_to user_path(user)

  end

  def destroy
    PostComment.find_by(id: params[:id], user_id: params[:user_id]).destroy
    redirect_to user_path(params[:user_id])
  end
  private
  def post_comment_params
  	params.require(:post_comment).permit(:comment)
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    user = User.find(params[:user_id])
    favorite = current_user.favorites.new(user_id: user.id)
    favorite.save
    redirect_to user_path(user)
  end

  def destroy
    user = User.find(params[:user_id])
    favorite = current_user.favorites.find_by(user_id: user.id)
    favorite.destroy
    redirect_to user_path(user)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    user = User.find(params[:user_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.user_id = user.id
    comment.save
    redirect_to user_path(user)
  end

  def destroy
    PostComment.find_by(id: params[:id], user_id: params[:user_id]).destroy
    redirect_to user_path(params[:user_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    current_user.follow(@user.id)
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.unfollow(@user.id)
  end

  def follower
    @user = User.find(params[:user_id])
    @users = @user.following_user
  end

  def followed
    @user = User.find(params[:user_id])
    @users = @user.follower_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
  end
end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'ユーザー情報を更新しました。'
    else
      render :edit
    end
  end

  def create
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
  end
end

  private

  def user_params
    params.require(:user).permit(:name, :profile, :image, :postcode, :prefecture_name, :address_city, :address_street, :address_building)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/homes/about.html.erb
<h1>Homes#about</h1>
<p>Find me in app/views/homes/about.html.erb</p>

app/views/homes/top.html.erb
<div class="swiper-container">
<div class="swiper-wrapper">
	<div class="swiper-slide"><%= image_tag asset_path("home1.jpg") %></div>
	<div class="swiper-slide"><%= image_tag asset_path("home2.jpg") %></div>
	<div class="swiper-slide"><%= image_tag asset_path("home3.jpg") %></div>
	<div class="swiper-slide"><%= image_tag asset_path("home4.jpg") %></div>
</div>
	<div class="swiper-pagination"></div>
</div>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= j(render 'users/unfollow', user: @user) %>")

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= j(render 'users/follow', user: @user) %>")

app/views/relationships/followed.html.erb
<div class ="body">
	<div class ="container">
	<h2 class="user__follower__title">Follower Users</h2>
	<% if @users.count > 0 %>
	  <%= render '/users/index', users: @users %>
	<% else %>
	  <p>ユーザーはいません</p>
	<% end %>
	</div>
</div>

app/views/relationships/follower.html.erb
<div class="body">
	<div class ="container">
	<h2 class="user__follow__title">Follow Users</h2>
	<% if @users.count > 0 %>
	  <%= render '/users/index', users: @users %>
	<% else %>
	  <p>ユーザーはいません</p>
	<% end %>
	</div>
</div>

app/views/users/_follow.html.erb
<%= link_to 'フォローする', user_relationships_path(user.id), method: :post, remote: true, class: "btn btn-success" %>

app/views/users/_unfollow.html.erb
<%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, remote: true, class: "btn btn-primary" %>

app/views/users/edit.html.erb
<div class="body">
	<div class ="container">
		<div class="row">
			 <%= form_for(@user) do |f| %>

		  <div class="user__text__field">
            <div class="field"><%= f.label :name %></div>
            <%= f.text_field :name, class: "name",size:75 %>
          </div>

          <div class="user__text__field">
            <div class="profile__field"><%= f.label :profile %></div>
            <%= f.text_area :profile, class: "profile", size: "20x10", class: "form-control"%>
          </div>
			<div><%= f.file_field :image %></div>
		　　<div class="user__text__field">
            <%= f.submit "プロフィールを変更する" , class: 'btn btn-success ' %></div>
		</div>
	</div>
	<% end %>
</div>

app/views/users/index.html.erb
<div class="body">
	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<div><% @users.each do |user|%> </div>
				<div><%= user.name %></div>
				<div><%= user.profile %></div>
				<div><%= link_to '詳細', user_path(user)%></div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="body">
	<div class="container">
		<p>
		  <strong>Image:</strong>
		  <% if @user.image? %>
		    <div class="thumbnail">
		      <%= image_tag @user.image.url %>
		    </div>
		  <% end %>
		</p>
		<sapn> <%= @user.name %> </sapn>
		<sapn> <%= @user.profile %> </sapn>


		<% if @user == current_user %>
		 <div><%= link_to '編集', edit_user_path(@user)%></div>
				<% end %>
		<div><%= link_to '一覧', users_path%></div>
<% if current_user != @user %>
  <span id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow', user: @user %>
    <% else %>
      <%= render 'follow', user: @user %>
    <% end %>
  <% end %>
</span>
<% if current_user != @user %>
  <span id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow', user: @user %>
    <% else %>
      <%= render 'follow', user: @user %>
    <% end %>
  </span>
<% end %>
<li>
  <i class="fa fa-comment"></i>
  <a href="#comments"><%= @user.post_comments.count %></a>
</li>
<div class="comment-list bt style-2" id="comments">
  <div class="float-wrapper">
    <h2 class="comment-count"><%= @user.post_comments.count %>件コメント</h2>
  </div>


<ol>
  <% @user.post_comments.each do |post_comment| %>
    <li class="comment">
      <div class="comment-body bb">
        <div class="comment-avatar">
        </div>
        <div class="comment-text">
          <div class="comment-author clearfix">
            <a href="#" class="link-author"><%= post_comment.user.name %></a>
            <span class="comment-meta">
              <span class="comment-date"><%= post_comment.created_at.strftime('%Y/%m/%d') %></span>
            </span>
          </div>
          <div class="comment-entry"><%= post_comment.comment %></div>
        </div>
      </div>
    </li>
  <% end %>
</ol>

<!-- <form class="mt-20"> -->
<%= form_for [@user, @post_comment] do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
    </div>
  </div>
       <% if @post_comment.user == current_user %>
            <div>
              <%= link_to "削除", user_post_comment_path(post_comment.user, post_comment), method: :delete, class: "btn btn-danger pull-right" %>
            </div>
          <% end %>
  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>
<!-- </form> -->

<% if @user.favorited_by?(current_user) %>
<li>
  <%= link_to user_favorite_path(@user), method: :delete do %>
    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= @user.favorites.count %> いいね
  <% end %>
</li>
<% else %>
<li>
  <%= link_to user_favorite_path(@user), method: :post do %>
    <i class="fa fa-heart-o" aria-hidden="true"></i>
    <%= @user.favorites.count %> いいね
  <% end %>
</li>
<% end %>

	</div>
</div>