config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'homes/about'
  resources :users, only: %i(show edit update index) do
    resource :relationships, only: %i(create destroy)
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
    resource :favorite, only: %i(create destroy)
    resources :post_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  mount_uploader :image, ImageUploader
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # フォロー機能
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def follow(user_id)
    follower.create!(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when User
      users_path
    end
   end

  def after_sihn_out_path_for(resource)
    case resource
    when User
      root_path
    end
   end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :post_code, :address, :email])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	user = User.find(params[:user_id])
  	comment = current_user.postcomments.new(post_comment_parms)
  	comment.user_id = user.id
  	comment.save
  	redirect_to user_path(user)

  end

  def destroy
    PostComment.find_by(id: params[:id], user_id: params[:user_id]).destroy
    redirect_to user_path(params[:user_id])
  end
  private
  def post_comment_params
  	params.require(:post_comment).permit(:comment)
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    user = User.find(params[:user_id])
    favorite = current_user.favorites.new(user_id: user.id)
    favorite.save
    redirect_to user_path(user)
  end

  def destroy
    user = User.find(params[:user_id])
    favorite = current_user.favorites.find_by(user_id: user.id)
    favorite.destroy
    redirect_to user_path(user)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    user = User.find(params[:user_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.user_id = user.id
    comment.save
    redirect_to user_path(user)
  end

  def destroy
    PostComment.find_by(id: params[:id], user_id: params[:user_id]).destroy
    redirect_to user_path(params[:user_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
  end
end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'ユーザー情報を更新しました。'
    else
      render :edit
    end
  end

  def create
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
  end
end

  private

  def user_params
    params.require(:user).permit(:name, :profile, :image, :postcode, :prefecture_name, :address_city, :address_street, :address_building)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>

    <div id="nav-drawer">
      <input id="nav-input" type="checkbox" class="nav-unshown">
      <label id="nav-open" for="nav-input"><span></span></label>
      <label class="nav-unshown" id="nav-close" for="nav-input"></label>
      <div id="nav-content">ここに中身を入れる</div>
  </div>
  <nav>
    <ul class="nav navbar-nav navbar-right menu">
      <% if user_signed_in? %>
        <li><%= link_to ' Home',user_path(current_user),class: 'glyphicon glyphicon-home home' %></li>
        <li><%= link_to 'logout', destroy_user_session_path, method: :delete,class: 'glyphicon glyphicon-log-out logout' %></li>
      <% else %>
        <li><%= link_to 'Home',root_path,class: 'glyphicon glyphicon-home home' %></li>
        <li><%= link_to 'About',homes_about_path,class: 'glyphicon glyphicon-link about' %></li>
        <li><%= link_to 'sign up', new_user_registration_path,class: 'glyphicon glyphicon-edit sign_up' %></li>
        <li><%= link_to 'login', new_user_session_path ,class: 'glyphicon glyphicon-log-in sign_in'%></li>
        </ul>
        <% end %>
    </nav>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Breake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- font awosme -->
    <script src="https://kit.fontawesome.com/f4a34d9917.js" crossorigin="anonymous"></script>
    <!--  スライド 　　　 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.1/css/swiper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.1/js/swiper.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/f4a34d9917.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <span id="back">
      <a href="#">
        <%= image_tag asset_path("logo.png")%>

      </a>
    </span>
    <%= yield %>
  </body>
</html>